# Generated by Django 2.0.5 on 2018-05-09 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='data',
            name='file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
