# Generated by Django 2.0.5 on 2018-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180509_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AlterField(
            model_name='data',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
    ]
