# Generated by Django 2.0.6 on 2018-06-14 13:16

import django.core.validators
from django.db import migrations, models
import upload.models
import upload.validator


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180509_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dataname',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]+$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='file_path',
            field=models.FileField(upload_to=upload.models.user_directory_path, validators=[upload.validator.validate_file_extension]),
        ),
    ]
